name: Build and Push to Artifact Registry

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
  # Trigger workflow manually from the GitHub Actions UI
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate GCP service account
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_ARTIFACT_CREDENTIALS }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_ARTIFACT_PROJECT_ID }}

      - name: Authenticate Docker with Google Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev
      
      # Export the Firebase admin sdk private key to a file
      - name: Create Service Account Key File
        run: |
          mkdir -p ./backend/split-app/secrets
          echo "${{ secrets.FIREBASE_ADMIN_SDK_WEB }}" > ./backend/split-app/secrets/split-app-firebase-adminsdk.json

      - name: Build Docker image
        run: |
          docker build -t "us-central1-docker.pkg.dev/${{ secrets.GCP_ARTIFACT_PROJECT_ID }}/apptohelpme-docker/split-app-backend:${{ github.sha }}" -f ./backend/split-app/Dockerfile ./backend/split-app

      - name: Push Docker image to Google Artifact Registry
        run: |
          docker push "us-central1-docker.pkg.dev/${{ secrets.GCP_ARTIFACT_PROJECT_ID }}/apptohelpme-docker/split-app-backend:${{ github.sha }}"
